### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by carlotita22** [cchen-cc/MA-SAM#2]
Thank you very much for the work, it is very good, could I use my own data? I have the data (MRI 3D) and the labels.

**Comment by cchen-cc** [comment]
Yes, definitely you can use your own data. I will upload my preprocessing script for MRI prostate data, which you can use as  a reference for preparing your own data.

**Comment by carlotita22** [comment]
ohhh thanks you! but I used the other code (BTCV dataset) , but I dont know if is possible.

Anyway, what is the structure of the prostate data?, becuase i used this: 

Img 
      img0001.nii
      img0002.ni
      ....

Label
     label0001.nii
     label0002.nii
     label0003.nii
     .....

**Comment by carlotita22** [comment]
I tried the training (with ViT_B) but i had a error: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/workspace/cgrivera/segunda_opcion/MA-SAM/MA-SAM/train.py", line 77, in <module>
    sam, img_embedding_size = sam_model_registry[args.vit_name](image_size=args.img_size,
  File "/mnt/workspace/cgrivera/segunda_opcion/MA-SAM/MA-SAM/segment_anything/build_sam.py", line 18, in build_sam_vit_h
    return _build_sam(
  File "/mnt/workspace/cgrivera/segunda_opcion/MA-SAM/MA-SAM/segment_anything/build_sam.py", line 135, in _build_sam
    new_state_dict = load_from(sam, state_dict, image_size, vit_patch_size, encoder_global_attn_indexes)
  File "/mnt/workspace/cgrivera/segunda_opcion/MA-SAM/MA-SAM/segment_anything/build_sam.py", line 162, in load_from
    rel_pos_params = new_state_dict[k]
KeyError: 'image_encoder.blocks.15.attn.rel_pos_h'

**Comment by cchen-cc** [comment]
Please check the structure of the prostate data by downloading the data from this link (https://liuquande.github.io/SAML/)
